version: '3.8'

services:
  backend:
    image: 2mukee/fc-backend:1.0
    ports:
      - 8080:8096
    environment:
      - TZ=Asia/Seoul
    deploy:
      mode: replicated
      replicas: 3
      update_config:
        parallelism: 3
        delay: 10s
        order: stop-first
        failure_action: rollback

  frontend:
    image: 2mukee/fc-frontend:1.0
    ports: 
      - 8088:80
    environment:
      - TZ=Asia/Seoul
    deploy:
      mode: replicated
      replicas: 6
      update_config:
        parallelism: 6
        delay: 10s
        order: start-first
        failure_action: rollback