version: '3.8'

services:
  backend:
    image: 2mukee/fc-backend:1.0
    ports:
      - 8080:8096
    environment:
      - TZ=Asia/Seoul
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first
        failure_action: rollback\
    healthcheck:
      test: ["wine", "main.go"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 45s

  frontend:
    image: 2mukee/fc-frontend:1.0
    ports: 
      - 80:80
    environment:
      - TZ=Asia/Seoul
    deploy:
      mode: replicated
      replicas: 7
      update_config:
        parallelism: 7
        delay: 10s
        order: start-first
        failure_action: rollback
    healthcheck:
      test: ["curl", "-f", "http://localhost/", "||", "exit", "1"]
      interval: 1m
      timeout: 3s
      retries: 5